name: Python testing

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.9
            wagtail: wagtail>=5.2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/setup.cfg"
      - run: |
          pip install "${{ matrix.wagtail }}"
      - run: |
          python runtests.py
